### ISSUE TITLE
Can you take a couple screenshots or maybe even a GIF?

### ISSUE THREAD

**Issue by PySimpleGUI** [ModDayHippie/IdleGame#1]
Game?  

![image](https://user-images.githubusercontent.com/46163555/184509960-4a31fa76-7f4c-477f-8747-72529d32014c.png)

I wanna see!  Can you take some screenshots and add them to your readme?  I'm SURE your visitors would love to see what you've made.

**Comment by ModDayHippie** [comment]
![Screenshot 2023-09-05 151203](https://github.com/ModDayHippie/MDH-ClickerGame/assets/48167631/ca00385e-0823-486e-9803-b014739462f3)

still very much a wip. working on adding more to it soon

**Comment by PySimpleGUI** [comment]
> still very much a wip.

Same with all my projects 
![image](https://github.com/ModDayHippie/MDH-ClickerGame/assets/46163555/afd92977-c38b-4df5-b4ba-b520e2312f48)
